const CONFIG={email:"YOUR_EMAIL@example.com",telegram:"YOUR_TELEGRAM"};
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
const email=document.getElementById("emailLink");if(email)email.href=`mailto:${CONFIG.email}`;
const tg=document.querySelector(".social");if(tg)tg.href=`https://t.me/${CONFIG.telegram}`;
const menu=document.getElementById("menuBtn"),nav=document.getElementById("nav");
if(menu&&nav){menu.addEventListener("click",()=>nav.classList.toggle("open"));nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")))}
if("IntersectionObserver"in window){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>o.observe(e))}
const sections=[...document.querySelectorAll("main section")],links=[...document.querySelectorAll(".nav a")];
if(sections.length&&links.length)window.addEventListener("scroll",()=>{let c="home";sections.forEach(s=>{if(scrollY>=s.offsetTop-180)c=s.id});links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")===`#${c}`))});
const modal=document.getElementById("modal");if(modal){const mt=document.getElementById("modalTitle"),mtype=document.getElementById("modalType"),mx=document.getElementById("modalText");document.querySelectorAll(".project-card").forEach(card=>card.querySelector(".arrow")?.addEventListener("click",()=>{mt.textContent=tr(card.dataset.title);mtype.textContent=tr(card.dataset.type);mx.textContent=tr(card.dataset.text);modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}));const close=()=>{modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""};document.getElementById("modalClose")?.addEventListener("click",close);document.getElementById("modalBackdrop")?.addEventListener("click",close);document.addEventListener("keydown",e=>{if(e.key==="Escape")close()})}

// EN -> RU / HY translations. Technical terms remain in English where that is standard for the industry.
const rows=[
["Home","Главная","Գլխավոր"],["Services","Услуги","Ծառայություններ"],["Projects","Проекты","Նախագծեր"],["About","Обо мне","Իմ մասին"],["Contact","Контакты","Կապ"],
["HI, I'M BOGDAN","ПРИВЕТ, Я БОГДАН","ԲԱՐԵՎ, ԵՍ ԲՈԳԴԱՆՆ ԵՄ"],["DIGITAL","ЦИФРОВЫЕ","ԹՎԱՅԻՆ"],["SOLUTIONS","РЕШЕНИЯ","ԼՈՒԾՈՒՄՆԵՐ"],
["I help businesses turn ideas into practical digital products — from websites and Telegram bots to AI-powered automation and trading systems.","Помогаю бизнесу превращать идеи в практичные цифровые продукты — от сайтов и Telegram-ботов до AI-автоматизации и торговых систем.","Օգնում եմ բիզնեսներին գաղափարները վերածել գործնական թվային պրոդուկտների՝ կայքերից և Telegram բոտերից մինչև AI ավտոմատացում և թրեյդինգի համակարգեր։"],
["Explore services","Посмотреть услуги","Դիտել ծառայությունները"],["Contact me","Связаться со мной","Կապվել ինձ հետ"],["DIGITAL SOLUTIONS FOR BUSINESS","ЦИФРОВЫЕ РЕШЕНИЯ ДЛЯ БИЗНЕСА","ԹՎԱՅԻՆ ԼՈՒԾՈՒՄՆԵՐ ԲԻԶՆԵՍԻ ՀԱՄԱՐ"],
["Web Development","Разработка сайтов","Կայքերի մշակում"],["Websites, landing pages, web applications, CRM and API integrations.","Сайты, лендинги, веб-приложения, CRM и API-интеграции։","Կայքեր, լենդինգներ, վեբ հավելվածներ, CRM և API ինտեգրումներ։"],
["Telegram Bots","Telegram-боты","Telegram բոտեր"],["Custom bots for leads, orders, notifications, automation and integrations.","Боты для заявок, заказов, уведомлений, автоматизации и интеграций։","Բոտեր հայտերի, պատվերների, ծանուցումների, ավտոմատացման և ինտեգրումների համար։"],
["AI & Automation","AI и автоматизация","AI և ավտոմատացում"],["AI assistants, workflow automation, data processing and smart business tools.","AI-ассистенты, автоматизация процессов, обработка данных и умные бизнес-инструменты։","AI օգնականներ, գործընթացների ավտոմատացում, տվյալների մշակում և խելացի բիզնես գործիքներ։"],
["SEO & Digital Growth","SEO и цифровой рост","SEO և թվային աճ"],["Technical SEO, site structure, on-page optimization and growth roadmaps.","Техническое SEO, структура сайта, внутренняя оптимизация и планы роста։","Տեխնիկական SEO, կայքի կառուցվածք, ներքին օպտիմալացում և աճի ռազմավարություն։"],
["MT5 Trading Bots","Торговые боты MT5","MT5 թրեյդինգի բոտեր"],["Grid EA configuration, testing, optimization and practical setup.","Настройка, тестирование и оптимизация Grid EA для MT5։","Grid EA-ի կարգավորում, թեստավորում և օպտիմալացում MT5-ի համար։"],
["Selected Projects","Избранные проекты","Ընտրված նախագծեր"],["DIGITAL / TECH / BUSINESS","DIGITAL / TECH / BUSINESS","ԹՎԱՅԻՆ / ՏԵԽ / ԲԻԶՆԵՍ"],["WEB STUDIO","ВЕБ-СТУДИЯ","ՎԵԲ ՍՏՈՒԴԻԱ"],["View case","Смотреть кейс","Դիտել քեյսը"],
["Website Development & Digital Solutions","Разработка сайтов и цифровые решения","Կայքերի մշակում և թվային լուծումներ"],["Websites, web applications, CRM systems, API integrations, SEO and automation.","Сайты, веб-приложения, CRM, API-интеграции, SEO и автоматизация։","Կայքեր, վեբ հավելվածներ, CRM, API ինտեգրումներ, SEO և ավտոմատացում։"],
["Telegram Bot Development","Разработка Telegram-ботов","Telegram բոտերի մշակում"],["TELEGRAM / BOTS","TELEGRAM / БОТЫ","TELEGRAM / ԲՈՏԵՐ"],["AI Solutions & Process Automation","AI-решения и автоматизация процессов","AI լուծումներ և գործընթացների ավտոմատացում"],["AI / AUTOMATION","AI / АВТОМАТИЗАЦИЯ","AI / ԱՎՏՈՄԱՏԱՑՈՒՄ"],
["Trading Bot for MetaTrader 5","Торговый бот для MetaTrader 5","Թրեյդինգի բոտ MetaTrader 5-ի համար"],["A non-standard grid EA with configurable distance, timeframe, order size, RSI, drying, spread filter, hedge settings and manual control.","Нестандартный Grid EA с настройками дистанций, таймфреймов, размера ордеров, RSI, drying, фильтра спреда, хеджа и ручного управления։","Ոչ ստանդարտ Grid EA՝ distance, timeframe, order size, RSI, drying, spread filter, hedge և ձեռքով կառավարման կարգավորումներով։"],
["Custom grid EA with advanced settings and a manual control panel.","Кастомный Grid EA с расширенными настройками и панелью ручного управления։","Կաստոմ Grid EA՝ ընդլայնված կարգավորումներով և ձեռքով կառավարման վահանակով։"],
["Capabilities","Возможности","Հնարավորություններ"],["WHAT I WORK WITH","С ЧЕМ Я РАБОТАЮ","ԻՆՉԻ ՀԵՏ ԵՄ ԱՇԽԱՏՈՒՄ"],["Websites · CRM · APIs","Сайты · CRM · API","Կայքեր · CRM · API"],["Bots · APIs · Automation","Боты · API · Автоматизация","Բոտեր · API · Ավտոմատացում"],["AI Tools","AI-инструменты","AI գործիքներ"],["AI workflows · Agents · Content","AI-процессы · Агенты · Контент","AI գործընթացներ · Agent-ներ · Կոնտենտ"],["On-page · Structure · Analytics","On-page · Структура · Аналитика","On-page · Կառուցվածք · Վերլուծություն"],["Processes · Integrations · Bots","Процессы · Интеграции · Боты","Գործընթացներ · Ինտեգրումներ · Բոտեր"],["Grid · Testing · Optimization","Grid · Тестирование · Оптимизация","Grid · Թեստավորում · Օպտիմալացում"],
["I'm a digital specialist with 4+ years of experience in web studios, working on digital projects and business development.","Я digital-специалист с опытом 4+ года в веб-студии, где работал с digital-проектами и развитием бизнеса։","Ես թվային մասնագետ եմ՝ վեբ ստուդիաներում 4+ տարվա փորձով՝ թվային նախագծերի և բիզնեսի զարգացման ոլորտում։"],
["I have a technical background, learn new tools quickly and enjoy turning business ideas into practical digital solutions. My focus is where technology, digital and business meet.","У меня технический бэкграунд, я быстро осваиваю новые инструменты и превращаю бизнес-идеи в практичные цифровые решения. Мой фокус — на пересечении технологий, digital и бизнеса։","Ունեմ տեխնիկական հիմք, արագ եմ սովորում նոր գործիքներ և սիրում եմ բիզնես գաղափարները վերածել գործնական թվային լուծումների։ Իմ ֆոկուսը տեխնոլոգիաների, թվային աշխարհի և բիզնեսի հատման կետում է։"],
["Problem solving","Решение задач","Խնդիրների լուծում"],["Self-learning","Самообучение","Ինքնուսուցում"],["Teamwork","Командная работа","Թիմային աշխատանք"],["Results oriented","Ориентация на результат","Արդյունքի կողմնորոշում"],["LOCATION","ЛОКАЦИЯ","ԳՏՆՎԵԼՈՒ ՎԱՅՐ"],["Yerevan, Armenia","Ереван, Армения","Երևան, Հայաստան"],["EXPERIENCE","ОПЫТ","ՓՈՐՁ"],["4+ years in digital & web studio","4+ года в digital и веб-студии","4+ տարի digital և վեբ ստուդիայում"],["LANGUAGES","ЯЗЫКИ","ԼԵԶՈՒՆԵՐ"],["Russian — Native","Русский — родной","Ռուսերեն — մայրենի"],["English — B2 written / A2 spoken","Английский — B2 письменно / A2 устно","Անգլերեն — B2 գրավոր / A2 բանավոր"],["FOCUS","ФОКУС","ՖՈԿՈՒՍ"],["Web · Digital · AI · Automation · Bots","Web · Digital · AI · Автоматизация · Боты","Web · Digital · AI · Ավտոմատացում · Բոտեր"],
["GET IN TOUCH","СВЯЗАТЬСЯ СО МНОЙ","ԿԱՊՎԵՔ ԻՆՁ ՀԵՏ"],["Let's build","Давайте создадим","Եկեք ստեղծենք"],["something great.","что-то действительно крутое.","մի հիանալի բան։"],["Have a project in mind or want to discuss an opportunity?","Есть проект или хотите обсудить сотрудничество?","Ունե՞ք նախագիծ կամ ցանկանում եք քննարկել համագործակցություն։"],["Email me","Написать на Email","Գրել Email-ով"],["BUILD / IMPROVE / GROW","СОЗДАВАТЬ / УЛУЧШАТЬ / РАЗВИВАТЬ","ՍՏԵՂԾԵԼ / ԲԱՐԵԼԱՎԵԼ / ԱՃԵԼ"],["PROJECT","ПРОЕКТ","ՆԱԽԱԳԻԾ"],["CASE STUDY","КЕЙС","ՔԵՅՍ"],["Replace this area with screenshots, results and project details.","Здесь будут скриншоты, результаты и детали проекта։","Այստեղ կլինեն սքրինշոթներ, արդյունքներ և նախագծի մանրամասներ։"],
["Start a project","Начать проект","Սկսել նախագիծ"],["Discuss an idea","Обсудить идею","Քննարկել գաղափարը"],["Discuss a project","Обсудить проект","Քննարկել նախագիծը"],["Discuss MT5 project","Обсудить проект MT5","Քննարկել MT5 նախագիծը"],["Back home","На главную","Գլխավոր էջ"],["WHAT I BUILD","ЧТО Я СОЗДАЮ","ԻՆՉ ԵՄ ՍՏԵՂԾՈՒՄ"],["SOLUTIONS","РЕШЕНИЯ","ԼՈՒԾՈՒՄՆԵՐ"],["WHAT I DO","ЧТО Я ДЕЛАЮ","ԻՆՉ ԵՄ ԱՆՈՒՄ"],["CAPABILITIES","ВОЗМОЖНОСТИ","ՀՆԱՐԱՎՈՐՈՒԹՅՈՒՆՆԵՐ"],["PROCESS","ПРОЦЕСС","ԳՈՐԾԸՆԹԱՑ"],["Digital products with a practical purpose.","Цифровые продукты с понятной практической целью։","Գործնական նպատակ ունեցող թվային պրոդուկտներ։"],
["Business websites","Бизнес-сайты","Բիզնես կայքեր"],["Professional websites that explain the offer and convert visitors.","Профессиональные сайты, которые понятно показывают предложение и помогают получать заявки։","Պրոֆեսիոնալ կայքեր, որոնք ներկայացնում են առաջարկը և օգնում են ստանալ հայտեր։"],["Landing pages","Лендинги","Լենդինգ էջեր"],["Focused pages for products, services and campaigns.","Фокусные страницы для продуктов, услуг и рекламных кампаний։","Կենտրոնացված էջեր պրոդուկտների, ծառայությունների և արշավների համար։"],["Web applications","Веб-приложения","Վեբ հավելվածներ"],["Custom browser-based tools for specific workflows.","Кастомные браузерные инструменты под конкретные процессы։","Բրաուզերային անհատական գործիքներ կոնկրետ գործընթացների համար։"],["CRM & integrations","CRM и интеграции","CRM և ինտեգրումներ"],["Connect websites with CRM systems and external services.","Подключение сайтов к CRM и внешним сервисам։","Կայքերի միացում CRM համակարգերին և արտաքին ծառայություններին։"],["API integrations","API-интеграции","API ինտեգրումներ"],["Move data between the systems your business already uses.","Обмен данными между системами, которые уже использует бизнес։","Տվյալների փոխանակում ձեր բիզնեսում օգտագործվող համակարգերի միջև։"],["Reduce manual operations with connected digital workflows.","Сокращение ручной работы за счёт связанных цифровых процессов։","Ձեռքով աշխատանքի կրճատում՝ կապակցված թվային գործընթացների միջոցով։"],
["Lead generation","Генерация лидов","Հայտերի հավաքագրում"],["Collect and qualify leads directly in Telegram.","Собирайте и квалифицируйте заявки прямо в Telegram։","Հավաքեք և որակավորեք հայտերը անմիջապես Telegram-ում։"],["Orders & requests","Заказы и заявки","Պատվերներ և հայտեր"],["Automate booking, orders, applications and status updates.","Автоматизируйте бронирование, заказы, заявки и обновления статусов։","Ավտոմատացրեք ամրագրումները, պատվերները, հայտերը և կարգավիճակների թարմացումները։"],["Notifications","Уведомления","Ծանուցումներ"],["Send alerts to customers, staff or administrators.","Отправляйте уведомления клиентам, сотрудникам или администраторам։","Ուղարկեք ծանուցումներ հաճախորդներին, աշխատակիցներին կամ ադմինիստրատորներին։"],["Business automation","Автоматизация бизнеса","Բիզնեսի ավտոմատացում"],["Move repetitive workflows into a simple Telegram interface.","Перенесите повторяющиеся процессы в простой интерфейс Telegram։","Կրկնվող գործընթացները տեղափոխեք Telegram-ի պարզ ինտերֆեյս։"],["API integrations","API-интеграции","API ինտեգրումներ"],["Connect bots with CRM, websites, databases and third-party APIs.","Подключайте ботов к CRM, сайтам, базам данных и сторонним API։","Միացրեք բոտերը CRM-ին, կայքերին, տվյալների բազաներին և երրորդ կողմի API-ներին։"],["AI features","AI-функции","AI գործառույթներ"],["Add AI assistants, classification, generation and smart replies when useful.","Добавляйте AI-ассистентов, классификацию, генерацию и умные ответы там, где это полезно։","Ավելացրեք AI օգնականներ, դասակարգում, գեներացում և խելացի պատասխաններ, երբ դա օգտակար է։"],
["Useful bots, not just chat interfaces.","Полезные боты, а не просто чат-интерфейсы։","Օգտակար բոտեր, ոչ միայն չաթի ինտերֆեյսներ։"],["From idea to working bot.","От идеи до работающего бота։","Գաղափարից մինչև աշխատող բոտ։"],["Requirements","Требования","Պահանջներ"],["Define users, workflow and required integrations.","Определить пользователей, процесс и необходимые интеграции։","Սահմանել օգտատերերին, գործընթացը և անհրաժեշտ ինտեգրումները։"],["Architecture","Архитектура","Ճարտարապետություն"],["Choose the simplest reliable technical approach.","Выбрать простой и надёжный технический подход։","Ընտրել ամենապարզ և հուսալի տեխնիկական մոտեցումը։"],["Development","Разработка","Մշակում"],["Build the bot and connect the required services.","Разработать бота и подключить необходимые сервисы։","Մշակել բոտը և միացնել անհրաժեշտ ծառայությունները։"],["Testing & launch","Тестирование и запуск","Թեստավորում և գործարկում"],["Test key scenarios and prepare the bot for use.","Протестировать ключевые сценарии и подготовить бота к работе։","Թեստավորել հիմնական սցենարները և պատրաստել բոտը օգտագործման համար։"],
["AI assistants","AI-ассистенты","AI օգնականներ"],["Internal or customer-facing assistants for common tasks and questions.","Внутренние или клиентские ассистенты для типовых задач и вопросов։","Ներքին կամ հաճախորդների համար նախատեսված օգնականներ սովորական խնդիրների և հարցերի համար։"],["Workflow automation","Автоматизация процессов","Գործընթացների ավտոմատացում"],["Automate repetitive actions across websites, tools and business systems.","Автоматизировать повторяющиеся действия на сайтах, в инструментах и бизнес-системах։","Ավտոմատացնել կրկնվող գործողությունները կայքերում, գործիքներում և բիզնես համակարգերում։"],["Content workflows","Контент-процессы","Կոնտենտի գործընթացներ"],["Build repeatable AI-assisted processes for text and digital content.","Создавать повторяемые AI-процессы для текста и цифрового контента։","Ստեղծել կրկնվող AI-օգնությամբ գործընթացներ տեքստի և թվային կոնտենտի համար։"],["Data processing","Обработка данных","Տվյալների մշակում"],["Classify, transform and route information automatically.","Автоматически классифицировать, преобразовывать и направлять информацию։","Ավտոմատ դասակարգել, փոխակերպել և ուղղորդել տեղեկատվությունը։"],["API connections","API-подключения","API միացումներ"],["Connect AI services with your existing products and workflows.","Подключать AI-сервисы к существующим продуктам и процессам։","Միացնել AI ծառայությունները առկա պրոդուկտներին և գործընթացներին։"],["Custom solutions","Кастомные решения","Անհատական լուծումներ"],["Combine bots, web tools and AI into one practical system.","Объединять ботов, веб-инструменты и AI в одну практичную систему։","Միավորել բոտերը, վեբ գործիքները և AI-ն մեկ գործնական համակարգում։"],
["Structured SEO work focused on visibility, website quality and a clear path from search traffic to business goals.","Структурированная SEO-работа с фокусом на видимость, качество сайта и путь от поискового трафика к бизнес-целям։","Կառուցված SEO աշխատանք՝ տեսանելիության, կայքի որակի և որոնման տրաֆիկից դեպի բիզնես նպատակներ հստակ ճանապարհի վրա։"],["A structured approach to search visibility.","Структурированный подход к поисковой видимости։","Որոնման տեսանելիության կառուցվածքային մոտեցում։"],["Technical review","Технический аудит","Տեխնիկական աուդիտ"],["Identify structural and technical issues that affect search performance.","Выявить структурные и технические проблемы, влияющие на поисковую эффективность։","Բացահայտել կառուցվածքային և տեխնիկական խնդիրները, որոնք ազդում են որոնման արդյունքների վրա։"],["On-page SEO","Внутреннее SEO","On-page SEO"],["Improve page structure, metadata, headings and relevant content signals.","Улучшить структуру страниц, метаданные, заголовки и контентные сигналы։","Բարելավել էջերի կառուցվածքը, metadata-ն, վերնագրերը և բովանդակության ազդանշանները։"],["Site structure","Структура сайта","Կայքի կառուցվածք"],["Build logical navigation and information architecture for users and search engines.","Создать логичную навигацию и информационную архитектуру для пользователей и поисковых систем։","Ստեղծել տրամաբանական նավիգացիա և տեղեկատվական ճարտարապետություն օգտատերերի և որոնման համակարգերի համար։"],["Keyword research","Сбор семантики","Բանալի բառերի հետազոտություն"],["Map relevant search intent to pages and business priorities.","Связать поисковый спрос с нужными страницами и бизнес-приоритетами։","Համապատասխանեցնել որոնման մտադրությունը էջերին և բիզնես առաջնահերթություններին։"],["Analytics","Аналитика","Վերլուծություն"],["Track important search and website signals to guide improvements.","Отслеживать важные поисковые и сайт-сигналы для улучшений։","Հետևել որոնման և կայքի կարևոր ազդանշաններին՝ բարելավումները ուղղորդելու համար։"],["Growth roadmap","План роста","Աճի ճանապարհային քարտեզ"],["Prioritize SEO actions by impact, effort and business value.","Расставить SEO-задачи по влиянию, усилиям и бизнес-ценности։","SEO քայլերը դասավորել ըստ ազդեցության, ջանքերի և բիզնես արժեքի։"],
["Grid-based MetaTrader 5 solutions, configuration and optimization. The focus is on flexible parameters, testing and practical setup.","Grid-решения для MetaTrader 5, настройка и оптимизация. Фокус — гибкие параметры, тестирование и практическая настройка։","Grid լուծումներ MetaTrader 5-ի համար, կարգավորում և օպտիմալացում։ Ֆոկուսը ճկուն պարամետրերի, թեստավորման և գործնական կարգավորման վրա է։"],["Flexible grid logic and configuration.","Гибкая Grid-логика и настройка։","Ճկուն Grid տրամաբանություն և կարգավորում։"],["Grid parameters","Параметры Grid","Grid պարամետրեր"],["Configure distance, timeframe and order-size logic for grid levels.","Настроить дистанцию, таймфрейм и размер ордеров для уровней сетки։","Կարգավորել distance-ը, timeframe-ը և order size-ը Grid մակարդակների համար։"],["Risk settings","Настройки риска","Ռիսկի կարգավորումներ"],["Prepare different presets for conservative and higher-risk testing.","Подготовить разные пресеты для консервативного и более рискованного тестирования։","Պատրաստել տարբեր preset-ներ պահպանողական և ավելի բարձր ռիսկով թեստավորման համար։"],["Filters","Фильтры","Ֆիլտրեր"],["Use spread, trading time and other available filters.","Использовать фильтр спреда, времени торговли и другие доступные фильтры։","Օգտագործել spread-ի, առևտրի ժամանակի և այլ հասանելի ֆիլտրեր։"],["Hedge logic","Hedge-логика","Hedge տրամաբանություն"],["Configure hedge-related settings according to the strategy.","Настроить параметры хеджа в соответствии со стратегией։","Կարգավորել hedge-ի պարամետրերը՝ ըստ ռազմավարության։"],["Manual panel","Ручная панель","Ձեռքով կառավարման վահանակ"],["Control selected orders or add positions to a grid manually.","Управлять выбранными ордерами или вручную добавлять позиции в сетку։","Կառավարել ընտրված օրդերները կամ ձեռքով ավելացնել դիրքեր Grid-ում։"],["Testing & optimization","Тестирование и оптимизация","Թեստավորում և օպտիմալացում"],["Run backtests and compare parameter sets before deployment.","Проводить бэктесты и сравнивать наборы параметров перед запуском։","Կատարել backtest-ներ և համեմատել պարամետրերը գործարկումից առաջ։"]
];
const dict={ru:{},hy:{}};rows.forEach(r=>{dict.ru[r[0]]=r[1];dict.hy[r[0]]=r[2]});
const original=new WeakMap();document.querySelectorAll("body *").forEach(el=>{if(el.children.length===0)original.set(el,el.textContent)});
function tr(s){const l=localStorage.getItem("siteLang")||"en";return l==="en"?s:(dict[l]?.[s]||s)}
function applyLang(lang){document.querySelectorAll("body *").forEach(el=>{if(el.children.length===0&&original.has(el)){const s=original.get(el);el.textContent=lang==="en"?s:(dict[lang]?.[s]||s)}});document.documentElement.lang=lang;document.querySelectorAll(".lang-switch button").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));localStorage.setItem("siteLang",lang)}
function addLangSwitch(){const h=document.querySelector(".header");if(!h||document.querySelector(".lang-switch"))return;const d=document.createElement("div");d.className="lang-switch";d.innerHTML='<button data-lang="ru">RU</button><button data-lang="en">EN</button><button data-lang="hy">ՀԱՅ</button>';d.querySelectorAll("button").forEach(b=>b.onclick=()=>applyLang(b.dataset.lang));h.appendChild(d)}
addLangSwitch();applyLang(localStorage.getItem("siteLang")||"en");